#!/bin/bash

reset

BUILDER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NERVA_DIR=$(dirname $BUILDER_DIR)
source ${BUILDER_DIR}/helpers

detectos
detectversion

if [ -z ${BUILD_TYPE} ]; then
	export BUILD_TYPE=debug
fi

mkdir -p ${BUILDER_DIR}/build/dev/${BUILD_TYPE}
cd ${BUILDER_DIR}/build/dev/${BUILD_TYPE}

cmake -D CMAKE_BUILD_TYPE=${BUILD_TYPE} -D NO_AES=OFF -D BUILD_TAG=${NERVA_BUILD_OS} ../../../..
make -j4
